-- =============================================
-- Author:  	Julian Barragan Verano
-- Create date: 07-MAY-2015
-- Description: CREATE TABLES Project CPyMES - IVR
-- Name SQL: 004_CPyMES.sql
-- =============================================


-- Tabla de Alarmas de Correlacion de CPYMES al IVR
CREATE TABLE KOU_ADM.ALARMA_PYMES 
(
  ID_ALARMA_PYMES NUMBER(12) NOT NULL 
, TICKET_ONIX VARCHAR2(32) 
, IP VARCHAR2(32) NOT NULL 
, CLASE_EQUIPO VARCHAR2(32) NOT NULL 
, TIPO_EVENTO VARCHAR2(32) NOT NULL 
, CIUDAD VARCHAR2(64) NOT NULL 
, DIVISION VARCHAR2(220) 
, FECHA_INICIO DATE NOT NULL 
, FECHA_ESPERANZA DATE NOT NULL 
, FECHA_FIN DATE 
, TIEMPO_TOTAL_FALLA NUMBER(4) 
, FECHA_MODIFICACION DATE 
, USUARIO_MODIFICACION VARCHAR2(50) 
, CODIGO_AUDIO_IVR NUMBER(4) 
, ESTADO_ALARMA VARCHAR2(20) NOT NULL 
, CONSTRAINT ALARMA_PYMES_PK PRIMARY KEY 
  (
    ID_ALARMA_PYMES 
  )
  ENABLE 
) INITRANS 16 TABLESPACE KOU_DAT;

COMMENT ON COLUMN ALARMA_PYMES.ID_ALARMA_PYMES IS 'Identificador de la tabla';

COMMENT ON COLUMN ALARMA_PYMES.TICKET_ONIX IS 'Aviso para revision de incidente';

COMMENT ON COLUMN ALARMA_PYMES.IP IS 'IP del equipo afectado';

COMMENT ON COLUMN ALARMA_PYMES.CLASE_EQUIPO IS 'Descripcion del equipo afectado';

COMMENT ON COLUMN ALARMA_PYMES.TIPO_EVENTO IS 'Tipo de evento';

COMMENT ON COLUMN ALARMA_PYMES.CIUDAD IS 'Ciudad donde se presenta la fall';

COMMENT ON COLUMN ALARMA_PYMES.DIVISION IS 'Division';

COMMENT ON COLUMN ALARMA_PYMES.FECHA_INICIO IS 'Fecha de generacion de la alarma';

COMMENT ON COLUMN ALARMA_PYMES.FECHA_ESPERANZA IS 'Fecha de esperada de recuperacion';

COMMENT ON COLUMN ALARMA_PYMES.FECHA_FIN IS 'Fecha de correcion de la alarma';

COMMENT ON COLUMN ALARMA_PYMES.TIEMPO_TOTAL_FALLA IS 'Tiempo en horas que demoro la falla en ser soluciionada';

COMMENT ON COLUMN ALARMA_PYMES.FECHA_MODIFICACION IS 'Fecha de modificacion';

COMMENT ON COLUMN ALARMA_PYMES.USUARIO_MODIFICACION IS 'Usuario de modicacion';

COMMENT ON COLUMN ALARMA_PYMES.CODIGO_AUDIO_IVR IS 'Numero de alarma que se reproducira al cliente';

COMMENT ON COLUMN ALARMA_PYMES.ESTADO_ALARMA IS 'Estado de la alarma';

ALTER TABLE KOU_ADM.ALARMA_PYMES 
ADD (DESCRIPCION_ALARMA LONG);


COMMENT ON COLUMN ALARMA_PYMES.DESCRIPCION_ALARMA IS 'Descripcion de la alarma';

-- Creacion de Sininimos de la Tabla ALARMA_PYMES
CREATE PUBLIC SYNONYM ALARMA_PYMES FOR KOU_ADM.ALARMA_PYMES;



-- Tabla de Alarmas de Servicio Nit, que relaciona las alarmas con los Codigos de Servicio y el NIT
CREATE TABLE KOU_ADM.ALARMA_PYMES_SERVICIO_NIT 
(
  ID_ALARMA_SERVICIO_NIT NUMBER(12) NOT NULL 
, ID_ALARMA_PYMES NUMBER(12) NOT NULL 
, CODIGO_SERVICIO VARCHAR2(10) NOT NULL 
, NIT VARCHAR2(15) NOT NULL 
, CONSTRAINT ALARMA_PYMES_SERVICIO_NIT_PK PRIMARY KEY 
  (
    ID_ALARMA_SERVICIO_NIT 
  )
  ENABLE 
) INITRANS 16 TABLESPACE KOU_DAT;

COMMENT ON COLUMN ALARMA_PYMES_SERVICIO_NIT.ID_ALARMA_SERVICIO_NIT IS 'Identificador de la tabla';

COMMENT ON COLUMN ALARMA_PYMES_SERVICIO_NIT.ID_ALARMA_PYMES IS 'FK con la tabla ALARMA_PYMES';

COMMENT ON COLUMN ALARMA_PYMES_SERVICIO_NIT.CODIGO_SERVICIO IS 'Codigo del servicio afectado';

COMMENT ON COLUMN ALARMA_PYMES_SERVICIO_NIT.NIT IS 'NIT del Cliente con servicio afectado';

CREATE PUBLIC SYNONYM ALARMA_PYMES_SERVICIO_NIT FOR KOU_ADM.ALARMA_PYMES_SERVICIO_NIT;


-- Creacion llave foranea a tabla ALARMA_PYMES
ALTER TABLE KOU_ADM.ALARMA_PYMES_SERVICIO_NIT
ADD CONSTRAINT ALARMA_PYMES_SERVICIO_NIT_FK1 FOREIGN KEY
(
  ID_ALARMA_PYMES 
)
REFERENCES KOU_ADM.ALARMA_PYMES
(
  ID_ALARMA_PYMES 
)
ENABLE;

CREATE INDEX KOU_ADM.CODIGO_SERVICIO_INDEX ON ALARMA_PYMES_SERVICIO_NIT (CODIGO_SERVICIO);

CREATE INDEX KOU_ADM.NIT_INDEX ON ALARMA_PYMES_SERVICIO_NIT (NIT);

-- Creacion de la vista ALARMA_PYMES_VIEW
CREATE VIEW KOU_ADM.ALARMA_PYMES_VIEW AS SELECT 
  A.ID_ALARMA_PYMES,
  A.TICKET_ONIX,
  A.CLASE_EQUIPO,
  A.DESCRIPCION_ALARMA,
  A.TIPO_EVENTO,
  A.CIUDAD,
  A.DIVISION,
  TO_CHAR(A.FECHA_INICIO, 'DD-MON-YYYY') AS FECHA_INICIO,
  TO_CHAR(A.FECHA_INICIO, 'HH24:MI:SS') AS HORA_INICIO,
  TO_CHAR(A.FECHA_ESPERANZA, 'DD-MON-YYYY') AS FECHA_ESPERANZA,
  TO_CHAR(A.FECHA_ESPERANZA, 'HH24:MI:SS') AS HORA_ESPERANZA,
  TO_CHAR(A.FECHA_FIN, 'DD-MON-YYYY') AS FECHA_FIN,
  TO_CHAR(A.FECHA_FIN, 'HH24:MI:SS') AS HORA_FIN,
  A.TIEMPO_TOTAL_FALLA,
  TO_CHAR(A.FECHA_MODIFICACION, 'DD-MON-YYYY') AS FECHA_MODIFICACION,
  TO_CHAR(A.FECHA_MODIFICACION, 'HH24:MI:SS') AS HORA_MODIFICACION,
  A.USUARIO_MODIFICACION,
  SN.CODIGO_SERVICIO,
  SN.NIT,
  A.ESTADO_ALARMA
FROM 
  KOU_ADM.ALARMA_PYMES A
JOIN KOU_ADM.ALARMA_PYMES_SERVICIO_NIT SN ON (A.ID_ALARMA_PYMES = SN.ID_ALARMA_PYMES );

CREATE PUBLIC SYNONYM ALARMA_PYMES_VIEW FOR KOU_ADM.ALARMA_PYMES_VIEW;


CREATE SEQUENCE KOU_ADM.ALARMA_PYMES_SERVICIO_NIT_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE KOU_ADM.ALARMA_PYMES_SEQ
INCREMENT BY 1
START WITH 1;
